---
name: zoblastoma-os
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/bluefin-dx
image-version: stable

modules:
  - type: rpm-ostree
    repos:
      - https://repository.mullvad.net/rpm/stable/mullvad.repo
    keys:
      - https://github.com/evilsocket/opensnitch/releases/download/v1.6.8/gustavo_iniguez_goia.asc
    optfix:
      - Mullvad VPN
      - megasync
      - Filen
    install:
      - mullvad-vpn
      - mullvad-browser
      - syncthing
      - https://mega.nz/linux/repo/Fedora_41/x86_64/megasync-Fedora_41.x86_64.rpm
      - https://mega.nz/linux/repo/Fedora_41/x86_64/nautilus-megasync-Fedora_41.x86_64.rpm
      - https://cdn.filen.io/@filen/desktop/release/latest/Filen_linux_x86_64.rpm
      - https://github.com/evilsocket/opensnitch/releases/download/v1.6.6/opensnitch-1.6.6-1.x86_64.rpm
      - https://github.com/evilsocket/opensnitch/releases/download/v1.6.8/opensnitch-ui-1.6.8-1.noarch.rpm
  - type: script
    scripts:
      - example.sh
    snippets:
      - "echo 'snippets commands run after the scripts section'"
  - type: signing # this sets up the proper policy & signing files for signed images to work fully