---
name: zoblastoma-os
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/bluefin-dx
image-version: gts

modules:
  - type: rpm-ostree
    repos:
      - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
      - https://repository.mullvad.net/rpm/stable/mullvad.repo
    keys:
      - https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
      - https://github.com/evilsocket/opensnitch/releases/download/v1.6.8/gustavo_iniguez_goia.asc
    optfix:
      - Mullvad VPN
      - brave.com
      - megasync
      - Filen
      - FreeTube
    install:
      - mullvad-vpn
      - mullvad-browser
      - brave-browser
      - syncthing
      - https://github.com/FreeTubeApp/FreeTube/releases/download/v0.23.5-beta/freetube-0.23.5.amd64.rpm
      - https://mega.nz/linux/repo/Fedora_41/x86_64/megasync-Fedora_41.x86_64.rpm
      - https://mega.nz/linux/repo/Fedora_41/x86_64/nautilus-megasync-Fedora_41.x86_64.rpm
      - https://cdn.filen.io/@filen/desktop/release/latest/Filen_linux_x86_64.rpm
      - https://github.com/evilsocket/opensnitch/releases/download/v1.7.2/opensnitch-1.7.2-1.x86_64.rpm
      - https://github.com/evilsocket/opensnitch/releases/download/v1.7.2/opensnitch-ui-1.7.2-1.noarch.rpm
  - type: script
    scripts:
      - example.sh
    snippets:
      - "echo 'snippets commands run after the scripts section'"
  - type: signing # this sets up the proper policy & signing files for signed images to work fully