---
name: zoblastoma-os
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/bluefin-dx
image-version: stable

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  - type: rpm-ostree
    repos:
      - https://repository.mullvad.net/rpm/stable/mullvad.repo
    optfix:
      - Mullvad VPN
    install:
      - mullvad-vpn
      - mullvad-browser
  - type: signing # this sets up the proper policy & signing files for signed images to work fully