---
name: zoblastoma-os
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/bluefin-dx
image-version: stable

modules:
  - type: rpm-ostree
    repos:
      - https://repository.mullvad.net/rpm/stable/mullvad.repo
    optfix:
      - Mullvad VPN
    install:
      - mullvad-vpn
      - mullvad-browser
  - type: script
    snippets:
      - "echo 'This is an example shell script'"
    # scripts:
      # - myscript.sh # example: run config/scripts/myscript.sh
  - type: signing # this sets up the proper policy & signing files for signed images to work fully